class Point
{
	// This code was generated by a tool. 
	int x;
	int y;
	int state;

	Point(int xt, int yt, int statet)
	{
		x=xt;
		y=yt;
		state=statet;
	}

	boolean equalsPosition(Point q)
	{
		return x==q.x && y==q.y;
	}

	void setState(int player)
	{
		state=player;
	}

	int getState()
	{
		return state;
	}

}

